name: nfs-tester
services:
  - name: app
    dockerfile_path: Dockerfile
    github:
      repo: thearyanahmed/nfs-tester
      branch: master
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
